### ISSUE TITLE
Slim Chrome Rendering With Menu Bar Disabled And On Flash Pages

### ISSUE THREAD

**Issue by Techy-Ben** [Quicksaver/The-Fox--Only-Better#106] opened 2015-06-19 17:42 UTC
Okay, these should be the last two issues from me for awhile. First, I hid my menu bar in order to make Firefox slimmer and look better, and when I did that caused the background alignment in slim chrome to break between the navigation toolbar and the bookmarks toolbar. I expected that, so I disabled/reenabled slim chrome, but the background was still slightly misaligned. I all my other add-ons, but the background was still misaligned. It's hard to see in a screenshot, so I made a video of it: http://youtu.be/KhHkjfwUGxs. (Private Video) Using slim chrome in Full Width mode solves the problem, and the other style options affect the alignment to different degrees.

The other problem occurs on flash pages like pixlr.com/editor. This may not be a bug, but may rather be inherent on flash pages.
![slim chrome draw issue](https://cloud.githubusercontent.com/assets/6982633/8259215/e427bcd4-1688-11e5-8d77-3d772b4ba943.png)

**Comment by Quicksaver** [comment] 2015-06-19 18:25
>  so I made a video of it: http://youtu.be/KhHkjfwUGxs. (Private Video)

You do know that if you make it private I'm not able to see it even if I have the link, right? ;) Anyway, the backgrounds are fine for me, so I guess I might really need that video...

> The other problem occurs on flash pages like pixlr.com/editor. This may not be a bug, but may rather be inherent on flash pages.

That's because of the fix I put in place for #53. It's also one of the things that can only be fixed once e10s arrives (hopefully), so I'll have to wait until then to do anything about it.

**Comment by Techy-Ben** [comment] 2015-06-20 02:12
Oops, sorry, I couldn't remember which setting allowed viewing of the video with the link only. I changed the video to unlisted, so you should be able to see it now.

**Comment by Quicksaver** [comment] 2015-06-20 07:32
That's weird, themes look fine for me, including that one. Could you try the add-on and the theme in a new profile and see if it also appears misaligned? If it does, you'll have to once again narrow down the cause in your main profile (other add-ons, buttons, stylesheets, etc).

**Comment by Techy-Ben** [comment] 2015-06-20 16:34
Yes, in a new profile with no settings changed and no add-ons other than TFOB and the theme Celebrate Americas Symbol, I still have the misalignment issue. Did you try these settings in TFOB?
![tfob settings](https://cloud.githubusercontent.com/assets/6982633/8268149/6c4d7fc6-1748-11e5-82ed-452e9cbe33b7.png)

Also, I have the Menu Bar disabled, Navigation Toolbar and Bookmarks Toolbar enabled, and the Bookmarks Toolbar is the only one deploying Slim Chrome.

I'm not sure what settings I could narrow it down too, since I replicated the issue in a completely clean profile...

**Comment by Quicksaver** [comment] 2015-06-22 10:11
I made some changes to the way the background image is placed. Can you tell if beta 10 (https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.1.14b10) helps at all with this?

**Comment by Techy-Ben** [comment] 2015-06-25 02:08
No, I still have the same issue, unfortunately.

**Comment by Quicksaver** [comment] 2015-06-25 09:15
The theme background issue? As the one in flash pages is impossible to fix at the moment like I said.

**Comment by Quicksaver** [comment] 2015-06-25 09:48
Hmm, I do see the issue in Firefox 38 (current release) but I don't see it in Firefox 39 (beta). Seeing as Fx39 is less than a week away from being released, I don't think it's necessary to fix this, it wouldn't make it in time for 38 anyway.

Let me know if you still have the issue when your firefox updates and I'll take another look.

**Closed** 2015-06-25 10:32 UTC
Labels: bug, minor
